fastapi:
  debug: true

api:
  versions:
    current: v1
    supported:
    deprecated:
    unsupported:

databases:
  default:
    ENGINE: "mongodb"
    DRIVER: "motor"
    NAME: "my_app_db"
    USER: "my_app_user"
    PASSWORD: "4dm1n4dm1n"
    HOST: "mongo"
    PORT: "27017"
