version: "3"
services:
  app:
    build: ./backend/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  # postgres as a service
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "4dm1n4dm1n"
      POSTGRES_DB: "my_db"
    volumes:
      - sql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sql_data:
